/**
 * src/countryNeighbors.js
 *
 * Table statique des voisins terrestres (frontières partagées) par ISO_A3.
 * Source : compilation Wikipédia "list of countries and territories by land borders".
 *
 * Les îles et pays sans voisin terrestre ont un tableau vide — on gère leur
 * accessibilité via un fallback distance-centroïde côté progression.js
 * (voir isCountryAccessible).
 */

export const NEIGHBORS = {
  // ================= EUROPE =================
  FRA: ['ESP', 'AND', 'BEL', 'LUX', 'DEU', 'CHE', 'ITA', 'MCO'],
  ESP: ['PRT', 'AND', 'FRA', 'GIB', 'MAR'],
  PRT: ['ESP'],
  AND: ['FRA', 'ESP'],
  MCO: ['FRA'],
  ITA: ['FRA', 'CHE', 'AUT', 'SVN', 'SMR', 'VAT'],
  SMR: ['ITA'],
  VAT: ['ITA'],
  CHE: ['FRA', 'DEU', 'AUT', 'LIE', 'ITA'],
  LIE: ['CHE', 'AUT'],
  AUT: ['DEU', 'CZE', 'SVK', 'HUN', 'SVN', 'ITA', 'CHE', 'LIE'],
  DEU: ['DNK', 'POL', 'CZE', 'AUT', 'CHE', 'FRA', 'LUX', 'BEL', 'NLD'],
  BEL: ['NLD', 'DEU', 'LUX', 'FRA'],
  LUX: ['BEL', 'DEU', 'FRA'],
  NLD: ['BEL', 'DEU'],
  GBR: ['IRL'],
  IRL: ['GBR'],
  DNK: ['DEU'],
  NOR: ['SWE', 'FIN', 'RUS'],
  SWE: ['NOR', 'FIN'],
  FIN: ['NOR', 'SWE', 'RUS'],
  EST: ['LVA', 'RUS'],
  LVA: ['EST', 'LTU', 'BLR', 'RUS'],
  LTU: ['LVA', 'BLR', 'POL', 'RUS'],
  POL: ['DEU', 'CZE', 'SVK', 'UKR', 'BLR', 'LTU', 'RUS'],
  CZE: ['DEU', 'POL', 'SVK', 'AUT'],
  SVK: ['CZE', 'POL', 'UKR', 'HUN', 'AUT'],
  HUN: ['AUT', 'SVK', 'UKR', 'ROU', 'SRB', 'HRV', 'SVN'],
  SVN: ['ITA', 'AUT', 'HUN', 'HRV'],
  HRV: ['SVN', 'HUN', 'SRB', 'BIH', 'MNE'],
  BIH: ['HRV', 'SRB', 'MNE'],
  SRB: ['HUN', 'ROU', 'BGR', 'MKD', 'ALB', 'MNE', 'BIH', 'HRV', 'KOS'],
  KOS: ['SRB', 'MKD', 'ALB', 'MNE'],
  MNE: ['HRV', 'BIH', 'SRB', 'KOS', 'ALB'],
  ALB: ['MNE', 'KOS', 'MKD', 'GRC'],
  MKD: ['KOS', 'SRB', 'BGR', 'GRC', 'ALB'],
  BGR: ['ROU', 'SRB', 'MKD', 'GRC', 'TUR'],
  ROU: ['UKR', 'MDA', 'BGR', 'SRB', 'HUN'],
  MDA: ['ROU', 'UKR'],
  UKR: ['POL', 'SVK', 'HUN', 'ROU', 'MDA', 'BLR', 'RUS'],
  BLR: ['LVA', 'LTU', 'POL', 'UKR', 'RUS'],
  GRC: ['ALB', 'MKD', 'BGR', 'TUR'],
  ISL: [],
  MLT: [],
  CYP: [],

  // ================= RUSSIA & CAUCASUS =================
  RUS: ['NOR', 'FIN', 'EST', 'LVA', 'LTU', 'POL', 'BLR', 'UKR', 'GEO', 'AZE', 'KAZ', 'CHN', 'MNG', 'PRK'],
  GEO: ['RUS', 'AZE', 'ARM', 'TUR'],
  ARM: ['GEO', 'AZE', 'IRN', 'TUR'],
  AZE: ['RUS', 'GEO', 'ARM', 'IRN', 'TUR'],
  TUR: ['GRC', 'BGR', 'GEO', 'ARM', 'AZE', 'IRN', 'IRQ', 'SYR'],

  // ================= MIDDLE EAST =================
  SYR: ['TUR', 'IRQ', 'JOR', 'ISR', 'LBN'],
  LBN: ['SYR', 'ISR'],
  ISR: ['LBN', 'SYR', 'JOR', 'EGY', 'PSE'],
  PSE: ['ISR', 'JOR', 'EGY'],
  JOR: ['SYR', 'IRQ', 'SAU', 'ISR', 'PSE'],
  IRQ: ['TUR', 'IRN', 'KWT', 'SAU', 'JOR', 'SYR'],
  IRN: ['IRQ', 'TUR', 'ARM', 'AZE', 'TKM', 'AFG', 'PAK'],
  KWT: ['IRQ', 'SAU'],
  SAU: ['JOR', 'IRQ', 'KWT', 'QAT', 'ARE', 'OMN', 'YEM', 'BHR'],
  BHR: ['SAU', 'QAT'],
  QAT: ['SAU', 'ARE'],
  ARE: ['SAU', 'OMN', 'QAT'],
  OMN: ['SAU', 'ARE', 'YEM'],
  YEM: ['SAU', 'OMN'],

  // ================= CENTRAL & SOUTH ASIA =================
  KAZ: ['RUS', 'CHN', 'KGZ', 'UZB', 'TKM'],
  UZB: ['KAZ', 'KGZ', 'TJK', 'AFG', 'TKM'],
  KGZ: ['KAZ', 'UZB', 'TJK', 'CHN'],
  TJK: ['UZB', 'KGZ', 'CHN', 'AFG'],
  TKM: ['KAZ', 'UZB', 'AFG', 'IRN'],
  AFG: ['IRN', 'TKM', 'UZB', 'TJK', 'CHN', 'PAK'],
  PAK: ['IRN', 'AFG', 'CHN', 'IND'],
  IND: ['PAK', 'CHN', 'NPL', 'BTN', 'BGD', 'MMR'],
  NPL: ['CHN', 'IND'],
  BTN: ['CHN', 'IND'],
  BGD: ['IND', 'MMR'],
  LKA: [],
  MDV: [],

  // ================= EAST & SOUTHEAST ASIA =================
  CHN: ['MNG', 'RUS', 'PRK', 'KAZ', 'KGZ', 'TJK', 'AFG', 'PAK', 'IND', 'NPL', 'BTN', 'MMR', 'LAO', 'VNM'],
  MNG: ['RUS', 'CHN'],
  PRK: ['CHN', 'KOR', 'RUS'],
  KOR: ['PRK'],
  JPN: [],
  TWN: [],
  MMR: ['CHN', 'IND', 'BGD', 'LAO', 'THA'],
  LAO: ['CHN', 'VNM', 'KHM', 'THA', 'MMR'],
  VNM: ['CHN', 'LAO', 'KHM'],
  KHM: ['THA', 'LAO', 'VNM'],
  THA: ['MMR', 'LAO', 'KHM', 'MYS'],
  MYS: ['THA', 'IDN', 'BRN', 'SGP'],
  SGP: ['MYS'],
  IDN: ['MYS', 'PNG', 'TLS'],
  BRN: ['MYS'],
  TLS: ['IDN'],
  PHL: [],

  // ================= AFRICA =================
  MAR: ['ESP', 'DZA', 'ESH'],
  ESH: ['MAR', 'DZA', 'MRT'],
  DZA: ['MAR', 'ESH', 'MRT', 'MLI', 'NER', 'LBY', 'TUN'],
  TUN: ['DZA', 'LBY'],
  LBY: ['TUN', 'DZA', 'NER', 'TCD', 'SDN', 'EGY'],
  EGY: ['LBY', 'SDN', 'ISR', 'PSE'],
  SDN: ['EGY', 'LBY', 'TCD', 'CAF', 'SSD', 'ETH', 'ERI'],
  SSD: ['SDN', 'ETH', 'KEN', 'UGA', 'COD', 'CAF'],
  ERI: ['SDN', 'ETH', 'DJI'],
  DJI: ['ERI', 'ETH', 'SOM'],
  ETH: ['ERI', 'DJI', 'SOM', 'KEN', 'SSD', 'SDN'],
  SOM: ['DJI', 'ETH', 'KEN'],
  KEN: ['ETH', 'SOM', 'TZA', 'UGA', 'SSD'],
  UGA: ['SSD', 'KEN', 'TZA', 'RWA', 'COD'],
  RWA: ['UGA', 'TZA', 'BDI', 'COD'],
  BDI: ['RWA', 'TZA', 'COD'],
  TZA: ['KEN', 'UGA', 'RWA', 'BDI', 'COD', 'ZMB', 'MWI', 'MOZ'],
  MOZ: ['TZA', 'MWI', 'ZMB', 'ZWE', 'ZAF', 'SWZ'],
  MWI: ['TZA', 'MOZ', 'ZMB'],
  ZMB: ['COD', 'TZA', 'MWI', 'MOZ', 'ZWE', 'BWA', 'NAM', 'AGO'],
  ZWE: ['ZMB', 'MOZ', 'ZAF', 'BWA'],
  BWA: ['ZMB', 'ZWE', 'ZAF', 'NAM'],
  NAM: ['AGO', 'ZMB', 'BWA', 'ZAF'],
  ZAF: ['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO'],
  LSO: ['ZAF'],
  SWZ: ['ZAF', 'MOZ'],
  AGO: ['COG', 'COD', 'ZMB', 'NAM'],
  COD: ['CAF', 'SSD', 'UGA', 'RWA', 'BDI', 'TZA', 'ZMB', 'AGO', 'COG'],
  COG: ['GAB', 'CMR', 'CAF', 'COD', 'AGO'],
  GAB: ['GNQ', 'CMR', 'COG'],
  GNQ: ['CMR', 'GAB'],
  CMR: ['NGA', 'TCD', 'CAF', 'COG', 'GAB', 'GNQ'],
  CAF: ['TCD', 'SDN', 'SSD', 'COD', 'COG', 'CMR'],
  TCD: ['LBY', 'SDN', 'CAF', 'CMR', 'NGA', 'NER'],
  NGA: ['NER', 'TCD', 'CMR', 'BEN'],
  BEN: ['TGO', 'BFA', 'NER', 'NGA'],
  TGO: ['GHA', 'BFA', 'BEN'],
  GHA: ['CIV', 'BFA', 'TGO'],
  CIV: ['LBR', 'GIN', 'MLI', 'BFA', 'GHA'],
  LBR: ['SLE', 'GIN', 'CIV'],
  SLE: ['GIN', 'LBR'],
  GIN: ['GNB', 'SEN', 'MLI', 'CIV', 'LBR', 'SLE'],
  GNB: ['SEN', 'GIN'],
  SEN: ['MRT', 'MLI', 'GIN', 'GNB', 'GMB'],
  GMB: ['SEN'],
  MRT: ['ESH', 'DZA', 'MLI', 'SEN'],
  MLI: ['DZA', 'NER', 'BFA', 'CIV', 'GIN', 'SEN', 'MRT'],
  BFA: ['MLI', 'NER', 'BEN', 'TGO', 'GHA', 'CIV'],
  NER: ['LBY', 'TCD', 'NGA', 'BEN', 'BFA', 'MLI', 'DZA'],
  MDG: [],
  MUS: [],
  COM: [],
  SYC: [],
  CPV: [],
  STP: [],

  // ================= AMERICAS =================
  CAN: ['USA'],
  USA: ['CAN', 'MEX'],
  MEX: ['USA', 'GTM', 'BLZ'],
  GTM: ['MEX', 'BLZ', 'HND', 'SLV'],
  BLZ: ['MEX', 'GTM'],
  SLV: ['GTM', 'HND'],
  HND: ['GTM', 'SLV', 'NIC'],
  NIC: ['HND', 'CRI'],
  CRI: ['NIC', 'PAN'],
  PAN: ['CRI', 'COL'],
  COL: ['PAN', 'VEN', 'BRA', 'PER', 'ECU'],
  VEN: ['COL', 'BRA', 'GUY'],
  GUY: ['VEN', 'BRA', 'SUR'],
  SUR: ['GUY', 'BRA', 'GUF'],
  GUF: ['SUR', 'BRA'],
  ECU: ['COL', 'PER'],
  PER: ['ECU', 'COL', 'BRA', 'BOL', 'CHL'],
  BRA: ['GUF', 'SUR', 'GUY', 'VEN', 'COL', 'PER', 'BOL', 'PRY', 'ARG', 'URY'],
  BOL: ['PER', 'BRA', 'PRY', 'ARG', 'CHL'],
  PRY: ['BOL', 'BRA', 'ARG'],
  URY: ['BRA', 'ARG'],
  ARG: ['CHL', 'BOL', 'PRY', 'BRA', 'URY'],
  CHL: ['PER', 'BOL', 'ARG'],
  CUB: [],
  HTI: ['DOM'],
  DOM: ['HTI'],
  JAM: [],
  BHS: [],
  PRI: [],
  TTO: [],
  BRB: [],
  GRD: [],
  LCA: [],
  VCT: [],
  ATG: [],
  DMA: [],
  KNA: [],

  // ================= OCEANIA =================
  AUS: [],
  NZL: [],
  PNG: ['IDN'],
  FJI: [],
  SLB: [],
  VUT: [],
  NCL: [],
  PYF: [],
  WSM: [],
  TON: [],
  KIR: [],
  MHL: [],
  FSM: [],
  PLW: [],
  NRU: [],
  TUV: [],

  // ================= AUTRES =================
  GRL: [],
  ATA: [],
  GIB: ['ESP'],
  FRO: [],
  IMN: [],
  JEY: [],
  GGY: [],
  ALA: [],
  BMU: [],
  FLK: [],
  SGS: [],
  ATF: [],
  IOT: [],
  SHN: [],
  REU: [],
  MYT: [],
  MSR: [],
  ABW: [],
  AIA: [],
  CYM: [],
  CUW: [],
  SXM: [],
  TCA: [],
  VGB: [],
  VIR: [],
  MAF: [],
  BLM: [],
  MTQ: [],
  GLP: [],
  ASM: [],
  COK: [],
  NFK: [],
  NIU: [],
  TKL: [],
  UMI: [],
  WLF: [],
  PCN: [],
  GUM: [],
  MNP: [],
  BVT: [],
  HMD: [],
  SPM: [],
  MAC: [],
  HKG: [],
}

/**
 * Fallback : deux pays sont considérés « voisins » si la distance angulaire
 * entre leurs centroïdes est inférieure à ce seuil (radians).
 * Utilisé UNIQUEMENT pour les îles isolées (NEIGHBORS[iso] vide) afin qu'elles
 * puissent être conquises depuis un pays continental proche.
 */
export const ISLAND_HOP_RADIUS = 0.25 // ~1400 km
